package amazon_filename;

public class Amazon_FileName extends javax.swing.JFrame {

    String DefaultString
            = "{SKU}-{Title Name}-{Language code}-main.mov"
            + "\n"
            + "\n"
            + "{SKU}-{Title Name}-{Language code}-trailer.mov"
            + "\n"
            + "\n"
            + "{SKU}-{Title Name}-en.srt"
            + "\n"
            + "\n"
            + "{SKU}-{Title Name}-cmn.srt"
            + "\n"
            + "\n"
            + "\n"
            + "{SKU}-{Title Name}-metadata.yaml"
            + "\n"
            + "\n"
            + "\n"
            + "{SKU}-{Title Name}-1575 x 2100.jpg"
            + "\n"
            + "{SKU}-{Title Name}-1400 x 2100.jpg"
            + "\n"
            + "{SKU}-{Title Name}-2048 x 1152.jpg";

    public void goChange() {
        String FinalString = "";
        String SKU = "";
        String TitleName = "";
        String LanguageCode = "";

        if (!T_SKU.getText().equals("")) {
            SKU = T_SKU.getText().trim();
        } else {
            SKU = "{SKU}";
        }

        if (!T_TitleName.getText().equals("")) {
            TitleName = T_TitleName.getText().trim();
        } else {
            TitleName = "{Title Name}";
        }

        if (!T_LanguageCode.getText().equals("")) {
            LanguageCode = T_LanguageCode.getText().trim();
        } else {
            LanguageCode = "{Language Code}";
        }

        FinalString = SKU + "-" + TitleName + "-" + LanguageCode + "-main.mov"
                + "\n"
                + "\n"
                + SKU + "-" + TitleName + "-" + LanguageCode + "-trailer.mov"
                + "\n"
                + "\n"
                + SKU + "-" + TitleName + "-en.srt"
                + "\n"
                + "\n"
                + SKU + "-" + TitleName + "-cmn.srt"
                + "\n"
                + "\n"
                + "\n"
                + SKU + "-" + TitleName + "-metadata.yaml"
                + "\n"
                + "\n"
                + "\n"
                + SKU + "-" + TitleName + "-1575 x 2100.jpg"
                + "\n"
                + SKU + "-" + TitleName + "-1400 x 2100.jpg"
                + "\n"
                + SKU + "-" + TitleName + "-2048 x 1152.jpg";
        T_Area.setText(FinalString);
    }

    public Amazon_FileName() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_SKU = new javax.swing.JLabel();
        T_SKU = new javax.swing.JTextField();
        T_TitleName = new javax.swing.JTextField();
        L_TtitleName = new javax.swing.JLabel();
        L_LanguageCode = new javax.swing.JLabel();
        T_LanguageCode = new javax.swing.JTextField();
        B_Clean = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_Area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amazon_FileName");

        L_SKU.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        L_SKU.setText("SKU：");

        T_SKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_SKUActionPerformed(evt);
            }
        });
        T_SKU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_SKUKeyReleased(evt);
            }
        });

        T_TitleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_TitleNameKeyReleased(evt);
            }
        });

        L_TtitleName.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        L_TtitleName.setText("Title Name：");

        L_LanguageCode.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        L_LanguageCode.setText("Language Code：");

        T_LanguageCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_LanguageCodeKeyReleased(evt);
            }
        });

        B_Clean.setText("清除");
        B_Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CleanActionPerformed(evt);
            }
        });

        T_Area.setColumns(20);
        T_Area.setRows(5);
        T_Area.setText("{SKU}-{Title Name}-{Language code}-main.mov\n\n{SKU}-{Title Name}-{Language code}-trailer.mov\n\n{SKU}-{Title Name}-en.srt\n\n{SKU}-{Title Name}-cmn.srt\n\n\n{SKU}-{Title Name}-metadata.yaml\n\n\n{SKU}-{Title Name}-1575 x 2100.jpg \n{SKU}-{Title Name}-1400 x 2100.jpg\n{SKU}-{Title Name}-2048 x 1152.jpg");
        jScrollPane1.setViewportView(T_Area);

        jLabel1.setText("正片：");

        jLabel2.setText("預告：");

        jLabel3.setText("字幕：");

        jLabel4.setText("Metadata：");

        jLabel5.setText("圖片：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_TtitleName)
                            .addComponent(L_LanguageCode)
                            .addComponent(L_SKU))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_Clean)
                            .addComponent(T_LanguageCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_SKU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_SKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_SKU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_TtitleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_LanguageCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_LanguageCode))
                .addGap(10, 10, 10)
                .addComponent(B_Clean)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_SKUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_SKUKeyReleased
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_T_SKUKeyReleased

    private void T_TitleNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_TitleNameKeyReleased
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_T_TitleNameKeyReleased

    private void T_LanguageCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_LanguageCodeKeyReleased
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_T_LanguageCodeKeyReleased

    private void B_CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CleanActionPerformed
        // TODO add your handling code here:
        String FinalString = "";
        T_SKU.setText("");
        T_TitleName.setText("");
        T_LanguageCode.setText("");

        T_Area.setText(DefaultString);
    }//GEN-LAST:event_B_CleanActionPerformed

    private void T_SKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_SKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_SKUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Amazon_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Amazon_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Amazon_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Amazon_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Amazon_FileName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Clean;
    private javax.swing.JLabel L_LanguageCode;
    private javax.swing.JLabel L_SKU;
    private javax.swing.JLabel L_TtitleName;
    private javax.swing.JTextArea T_Area;
    private javax.swing.JTextField T_LanguageCode;
    private javax.swing.JTextField T_SKU;
    private javax.swing.JTextField T_TitleName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
