/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Evan
 */
public class NotePad extends javax.swing.JFrame {

    /**
     * Creates new form NotePad
     */
    public NotePad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        M_New = new javax.swing.JMenuItem();
        M_Open = new javax.swing.JMenuItem();
        M_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        M_Search = new javax.swing.JMenuItem();
        M_Copy = new javax.swing.JMenuItem();
        M_Paste = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("檔案");

        M_New.setText("新增");
        M_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_NewActionPerformed(evt);
            }
        });
        jMenu1.add(M_New);

        M_Open.setText("開啟檔案");
        M_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_OpenActionPerformed(evt);
            }
        });
        jMenu1.add(M_Open);

        M_Exit.setText("關閉");
        M_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(M_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("編輯");

        M_Search.setText("搜尋");
        M_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_SearchActionPerformed(evt);
            }
        });
        jMenu2.add(M_Search);

        M_Copy.setText("複製");
        M_Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_CopyActionPerformed(evt);
            }
        });
        jMenu2.add(M_Copy);

        M_Paste.setText("貼上");
        M_Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_PasteActionPerformed(evt);
            }
        });
        jMenu2.add(M_Paste);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_NewActionPerformed
        // TODO add your handling code here:
        if (!jTextArea1.getText().equals("")) {
            int NewShowMessage = JOptionPane.showConfirmDialog(null, "是否存檔", "存檔?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            switch (NewShowMessage) {
                case JOptionPane.YES_OPTION:
                    JFileChooser NewJFC = new JFileChooser();
                    int returnValue = NewJFC.showOpenDialog(null);
                    if (returnValue == JFileChooser.APPROVE_OPTION) //判斷是否選擇檔案 
                    {
                        
                    }
                    break;
                case JOptionPane.NO_OPTION:
                    break;
            }
        }
    }//GEN-LAST:event_M_NewActionPerformed

    private void M_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_ExitActionPerformed
        // TODO add your handling code here:
        if (!jTextArea1.getText().equals("")) {
            int CloseResult = JOptionPane.showConfirmDialog(null, "是否關閉", "關閉", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            switch (CloseResult) {
                case JOptionPane.YES_OPTION:
                    System.exit(0);
                    break;
                case JOptionPane.NO_OPTION:
                    break;
            }
        }
        System.exit(0);
    }//GEN-LAST:event_M_ExitActionPerformed

    private void M_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_OpenActionPerformed
        // TODO add your handling code here:
        if (jTextArea1.getText().equals("")) {
            JFileChooser NewJFC = new JFileChooser();
            int returnValue = NewJFC.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) //判斷是否選擇檔案 
            {

            }
        }
    }//GEN-LAST:event_M_OpenActionPerformed

    private void M_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_SearchActionPerformed

    private void M_CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_CopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_CopyActionPerformed

    private void M_PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_PasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M_PasteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotePad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotePad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem M_Copy;
    private javax.swing.JMenuItem M_Exit;
    private javax.swing.JMenuItem M_New;
    private javax.swing.JMenuItem M_Open;
    private javax.swing.JMenuItem M_Paste;
    private javax.swing.JMenuItem M_Search;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
