
import java.awt.Dimension;
import java.awt.Toolkit;

public class GooglePlay_FileName extends javax.swing.JFrame {

    String Name;
    String Language;
    String ID;
    String FinalString;
    String CheckBuruIn;
    String CheckMLP;

    public void checkSelect() {
        if (jCheckBox_BurnIn.isSelected()) {
            CheckBuruIn = "Forced";
        } else {
            CheckBuruIn = "Fully";
        }

        if (jCheckBox_MLP.isSelected()) {
            CheckMLP = "MLP_";
        } else {
            CheckMLP = "";
        }
    }

    public void goChange() {
        //先執行勾選判斷
        checkSelect();

        if (!jTextFieldName.getText().equals("")) {
            Name = jTextFieldName.getText().trim();
        } else {
            Name = "(片名)";
        }

        if (!jTextFieldLanguage.getText().equals("")) {
            Language = jTextFieldLanguage.getText().trim();
        } else {
            Language = "(發音)";
        }

        if (!jTextFieldID.getText().equals("")) {
            ID = jTextFieldID.getText().trim();
        } else {
            ID = "(ContentID)";
        }

        FinalString = "AVJET_" + Name + "_cmn-TW_PosterArt_" + ID + "\n"
                + "\n"
                + "AVJET_" + Name + "_cmn-TW_Forced_" + ID + "\n"
                + "\n"
                + "AVJET_" + Name + "_cmn-TW_Full_" + ID + "\n"
                + "\n"
                + "AVJET_" + CheckMLP + Name + "_" + Language + "_" + CheckBuruIn + "_Feature_" + ID + "\n"
                + "\n"
                + "AVJET_" + Name + "_" + Language + "_Sub_Trailer_" + ID;
        jTextArea1.setText(FinalString);
    }

    public GooglePlay_FileName() {
        initComponents();

        //定義打開後視窗顯示在螢幕的初始位置
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) (screenSize.getWidth() - getWidth()) / 2, (int) (screenSize.getHeight() - getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldName = new javax.swing.JTextField();
        jTextFieldLanguage = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelName = new javax.swing.JLabel();
        jLabelLanguage = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jButtonClean = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox_BurnIn = new javax.swing.JCheckBox();
        jCheckBox_MLP = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Google Play - File Name");

        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyReleased(evt);
            }
        });

        jTextFieldLanguage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLanguageKeyReleased(evt);
            }
        });

        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyReleased(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("AVJET_(片名)_cmn-TW_PosterArt_(ContentID)\n\nAVJET_(片名)_cmn-TW_Forced_(ContentID)\n\nAVJET_(片名)_cmn-TW_Full_(ContentID)\n\nAVJET_(片名)_(發音)_Fully_Feature_(ContentID)\n\nAVJET_(片名)_(發音)_Sub_Trailer_(ContentID)");
        jScrollPane1.setViewportView(jTextArea1);

        jLabelName.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabelName.setText("片名：");

        jLabelLanguage.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabelLanguage.setText("發音：");

        jLabelID.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabelID.setText("ID：");

        jButtonClean.setText("清除");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabel1.setText("海報：");

        jLabel2.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabel2.setText("字卡：");

        jLabel3.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabel3.setText("字幕：");

        jLabel4.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabel4.setText("正片：");

        jLabel5.setFont(new java.awt.Font("新細明體", 1, 12)); // NOI18N
        jLabel5.setText("預告：");

        jCheckBox_BurnIn.setText("Burn In - 字幕");
        jCheckBox_BurnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BurnInActionPerformed(evt);
            }
        });

        jCheckBox_MLP.setText("MLP - 多語言音軌");
        jCheckBox_MLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_MLPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelLanguage)
                                .addComponent(jLabelID))
                            .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_BurnIn)
                                    .addComponent(jCheckBox_MLP)))
                            .addComponent(jButtonClean)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName)
                    .addComponent(jCheckBox_BurnIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLanguage)
                    .addComponent(jCheckBox_MLP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClean)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        // TODO add your handling code here:
        jTextFieldName.setText("");
        jTextFieldLanguage.setText("");
        jTextFieldID.setText("");
        jCheckBox_BurnIn.setSelected(false);
        jCheckBox_MLP.setSelected(false);

        checkSelect();

        FinalString = "AVJET_(片名)_cmn-TW_PosterArt_(ContentID)\n"
                + "\n"
                + "AVJET_(片名)_cmn-TW_Forced_(ContentID)\n"
                + "\n"
                + "AVJET_(片名)_cmn-TW_Full_(ContentID)\n"
                + "\n"
                + "AVJET_" + CheckMLP + "(片名)_(發音)_" + CheckBuruIn + "_Feature_(ContentID)\n"
                + "\n"
                + "AVJET_(片名)_(發音)_Sub_Trailer_(ContentID)";
        jTextArea1.setText(FinalString);
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jTextFieldNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyReleased
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_jTextFieldNameKeyReleased

    private void jTextFieldLanguageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLanguageKeyReleased
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_jTextFieldLanguageKeyReleased

    private void jTextFieldIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyReleased
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_jTextFieldIDKeyReleased

    private void jCheckBox_BurnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BurnInActionPerformed
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_jCheckBox_BurnInActionPerformed

    private void jCheckBox_MLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_MLPActionPerformed
        // TODO add your handling code here:
        goChange();
    }//GEN-LAST:event_jCheckBox_MLPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GooglePlay_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GooglePlay_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GooglePlay_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GooglePlay_FileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GooglePlay_FileName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClean;
    private javax.swing.JCheckBox jCheckBox_BurnIn;
    private javax.swing.JCheckBox jCheckBox_MLP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelLanguage;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLanguage;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
